In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import sklearn as sk

In [2]:
df = pd.read_csv("files/pred_final.csv")
df

obj_prg  obj_subprg   obj_key Кодзадачи  ПроцентЗавершенияЗадачи  \
0            0           0  022-0527         1                        0   
1            0           0  022-0354         1                        0   
2            0           1  022-0513         1                        0   
3            0           1  020-0684         1                        0   
4            0           1  019-0589         1                        0   
...        ...         ...       ...       ...                      ...   
35196        1           2  019-0477       7.4                       93   
35197        0           0  020-0710         8                        0   
35198        0           0  019-0675         8                        0   
35199        0           1  020-0712         8                        0   
35200        0           0  019-0429         8                        0   

      ДатаНачалаЗадачи ДатаОкончанияЗадачи  Статуспоэкспертизе  Экспертиза  \
0           2022-01-14          2023-03-30                   0           0   
1           2022-12-01          2023-07-27                   0           0   
2           2023-01-23          2023-09-29                   0           0   
3           2020-11-03          2022-02-01                   0           0   
4           2020-11-03          2022-05-16                   0           0   
...                ...                 ...                 ...         ...   
35196       2020-04-28          2023-05-31                   0           0   
35197       2023-08-31          2024-04-10                   0           0   
35198       2023-09-01          2024-04-11                   0           0   
35199       2023-06-19          2024-01-26                   0           0   
35200       2024-05-30          2024-12-31                   0           0   

      date_report  season  Скорость  Кол-во рабочих  Генподрядчик  \
0      2023-01-17       1  0.051988             0.0           0.0   
1      2023-01-17       1  0.224265             0.0           0.0   
2      2023-01-17       1  0.117271             0.0           0.0   
3      2023-01-17       4  0.000000             0.0           2.0   
4      2023-01-17       4  0.000000             0.0           2.0   
...           ...     ...       ...             ...           ...   
35196  2023-05-29       2  0.082447             5.0          12.0   
35197  2023-05-29       3  0.000000           156.0           5.0   
35198  2023-05-29       4  0.000000           139.0          22.0   
35199  2023-05-29       2  0.000000            53.0           5.0   
35200  2023-05-29       2  0.000000           107.0           7.0   

       Генпроектировщик  Время на выполнение  
0                   0.0                  440  
1                   0.0                  238  
2                   0.0                  249  
3                   1.0                  455  
4                   1.0                  559  
...                 ...                  ...  
35196              16.0                 1128  
35197               8.0                  223  
35198              33.0                  223  
35199               8.0                  221  
35200              11.0                  215  

[35201 rows x 16 columns]

In [3]:
df = df.sort_values(['obj_key', 'Кодзадачи', 'ПроцентЗавершенияЗадачи', 'date_report'])
df

obj_prg  obj_subprg   obj_key Кодзадачи  ПроцентЗавершенияЗадачи  \
8            0           1  017-0520         1                      100   
1699         0           1  017-0520         1                      100   
3432         0           1  017-0520         1                      100   
5219         0           1  017-0520         1                      100   
7030         0           1  017-0520         1                      100   
...        ...         ...       ...       ...                      ...   
33242        1           3  022-0631       7.4                        0   
35153        1           3  022-0631       7.4                        0   
1665         1           3  022-0631         8                        0   
3393         1           3  022-0631         8                        0   
5191         1           3  022-0631         8                        0   

      ДатаНачалаЗадачи ДатаОкончанияЗадачи  Статуспоэкспертизе  Экспертиза  \
8           2018-11-01          2022-02-15                   0           0   
1699        2018-11-01          2022-02-15                   0           0   
3432        2018-11-01          2022-02-15                   0           0   
5219        2018-11-01          2022-02-15                   0           0   
7030        2018-11-01          2022-02-15                   0           0   
...                ...                 ...                 ...         ...   
33242       2024-10-14          2024-11-11                   0           0   
35153       2024-10-14          2024-11-11                   0           0   
1665        2024-12-02          2025-07-11                   0           0   
3393        2024-12-02          2025-07-11                   0           0   
5191        2024-12-02          2025-07-11                   0           0   

      date_report  season  Скорость  Кол-во рабочих  Генподрядчик  \
8      2023-01-17       4  0.083195             0.0           5.0   
1699   2023-01-23       4  0.083195             0.0           5.0   
3432   2023-02-06       4  0.083195             0.0           5.0   
5219   2023-02-13       4  0.083195             0.0           5.0   
7030   2023-02-20       4  0.083195             0.0           5.0   
...           ...     ...       ...             ...           ...   
33242  2023-05-22       4  0.000000             0.0           2.0   
35153  2023-05-29       4  0.000000             0.0           2.0   
1665   2023-01-17       1  0.000000             0.0           2.0   
3393   2023-01-23       1  0.000000             0.0           2.0   
5191   2023-02-06       1  0.000000             0.0           2.0   

       Генпроектировщик  Время на выполнение  
8                   8.0                 1202  
1699                8.0                 1202  
3432                8.0                 1202  
5219                8.0                 1202  
7030                8.0                 1202  
...                 ...                  ...  
33242               1.0                   28  
35153               1.0                   28  
1665                0.0                  221  
3393                0.0                  221  
5191                0.0                  221  

[35201 rows x 16 columns]

In [4]:
lk = sk.preprocessing.LabelEncoder()
lk.fit(df["Кодзадачи"])
df["Кодзадачи"] = lk.transform(df["Кодзадачи"])
df

obj_prg  obj_subprg   obj_key  Кодзадачи  ПроцентЗавершенияЗадачи  \
8            0           1  017-0520          0                      100   
1699         0           1  017-0520          0                      100   
3432         0           1  017-0520          0                      100   
5219         0           1  017-0520          0                      100   
7030         0           1  017-0520          0                      100   
...        ...         ...       ...        ...                      ...   
33242        1           3  022-0631         26                        0   
35153        1           3  022-0631         26                        0   
1665         1           3  022-0631         27                        0   
3393         1           3  022-0631         27                        0   
5191         1           3  022-0631         27                        0   

      ДатаНачалаЗадачи ДатаОкончанияЗадачи  Статуспоэкспертизе  Экспертиза  \
8           2018-11-01          2022-02-15                   0           0   
1699        2018-11-01          2022-02-15                   0           0   
3432        2018-11-01          2022-02-15                   0           0   
5219        2018-11-01          2022-02-15                   0           0   
7030        2018-11-01          2022-02-15                   0           0   
...                ...                 ...                 ...         ...   
33242       2024-10-14          2024-11-11                   0           0   
35153       2024-10-14          2024-11-11                   0           0   
1665        2024-12-02          2025-07-11                   0           0   
3393        2024-12-02          2025-07-11                   0           0   
5191        2024-12-02          2025-07-11                   0           0   

      date_report  season  Скорость  Кол-во рабочих  Генподрядчик  \
8      2023-01-17       4  0.083195             0.0           5.0   
1699   2023-01-23       4  0.083195             0.0           5.0   
3432   2023-02-06       4  0.083195             0.0           5.0   
5219   2023-02-13       4  0.083195             0.0           5.0   
7030   2023-02-20       4  0.083195             0.0           5.0   
...           ...     ...       ...             ...           ...   
33242  2023-05-22       4  0.000000             0.0           2.0   
35153  2023-05-29       4  0.000000             0.0           2.0   
1665   2023-01-17       1  0.000000             0.0           2.0   
3393   2023-01-23       1  0.000000             0.0           2.0   
5191   2023-02-06       1  0.000000             0.0           2.0   

       Генпроектировщик  Время на выполнение  
8                   8.0                 1202  
1699                8.0                 1202  
3432                8.0                 1202  
5219                8.0                 1202  
7030                8.0                 1202  
...                 ...                  ...  
33242               1.0                   28  
35153               1.0                   28  
1665                0.0                  221  
3393                0.0                  221  
5191                0.0                  221  

[35201 rows x 16 columns]

In [5]:
y = np.array(df["Время на выполнение"])
y

array([1202, 1202, 1202, ...,  221,  221,  221], dtype=int64)

In [6]:
df.drop(['ДатаНачалаЗадачи', 'ДатаОкончанияЗадачи', 'date_report', 'Время на выполнение', 'obj_key', 'Кодзадачи'], axis=1, inplace=True)
df

obj_prg  obj_subprg  ПроцентЗавершенияЗадачи  Статуспоэкспертизе  \
8            0           1                      100                   0   
1699         0           1                      100                   0   
3432         0           1                      100                   0   
5219         0           1                      100                   0   
7030         0           1                      100                   0   
...        ...         ...                      ...                 ...   
33242        1           3                        0                   0   
35153        1           3                        0                   0   
1665         1           3                        0                   0   
3393         1           3                        0                   0   
5191         1           3                        0                   0   

       Экспертиза  season  Скорость  Кол-во рабочих  Генподрядчик  \
8               0       4  0.083195             0.0           5.0   
1699            0       4  0.083195             0.0           5.0   
3432            0       4  0.083195             0.0           5.0   
5219            0       4  0.083195             0.0           5.0   
7030            0       4  0.083195             0.0           5.0   
...           ...     ...       ...             ...           ...   
33242           0       4  0.000000             0.0           2.0   
35153           0       4  0.000000             0.0           2.0   
1665            0       1  0.000000             0.0           2.0   
3393            0       1  0.000000             0.0           2.0   
5191            0       1  0.000000             0.0           2.0   

       Генпроектировщик  
8                   8.0  
1699                8.0  
3432                8.0  
5219                8.0  
7030                8.0  
...                 ...  
33242               1.0  
35153               1.0  
1665                0.0  
3393                0.0  
5191                0.0  

[35201 rows x 10 columns]

In [7]:
cat_features = ['obj_prg', 'obj_subprg', 'Статуспоэкспертизе', 'season']

encoder = sk.preprocessing.OneHotEncoder()
encoded_features = encoder.fit_transform(df[cat_features])

# Сбрасываем индексы датафреймов
encoded_df = pd.DataFrame(encoded_features.toarray()).reset_index(drop=True)
df_no_cat = df.drop(cat_features, axis=1).reset_index(drop=True)

# Объединяем закодированные признаки и не-категориальные признаки
new_data = pd.concat([encoded_df, df_no_cat], axis=1)

df.drop(cat_features, inplace=True, axis=1)
new_data.columns = [str(col) for col in new_data.columns] # добавляем префикс к имени каждой колонки, чтобы избежать дубликатов
df = new_data.copy()
df

0    1    2    3    4    5    6    7    8    9   10   11   12  \
0      1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
1      1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
2      1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
3      1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
4      1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
35196  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
35197  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
35198  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
35199  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
35200  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   

       ПроцентЗавершенияЗадачи  Экспертиза  Скорость  Кол-во рабочих  \
0                          100           0  0.083195             0.0   
1                          100           0  0.083195             0.0   
2                          100           0  0.083195             0.0   
3                          100           0  0.083195             0.0   
4                          100           0  0.083195             0.0   
...                        ...         ...       ...             ...   
35196                        0           0  0.000000             0.0   
35197                        0           0  0.000000             0.0   
35198                        0           0  0.000000             0.0   
35199                        0           0  0.000000             0.0   
35200                        0           0  0.000000             0.0   

       Генподрядчик  Генпроектировщик  
0               5.0               8.0  
1               5.0               8.0  
2               5.0               8.0  
3               5.0               8.0  
4               5.0               8.0  
...             ...               ...  
35196           2.0               1.0  
35197           2.0               1.0  
35198           2.0               0.0  
35199           2.0               0.0  
35200           2.0               0.0  

[35201 rows x 19 columns]

In [8]:
x = np.array(df)
x

array([[1., 0., 0., ..., 0., 5., 8.],
       [1., 0., 0., ..., 0., 5., 8.],
       [1., 0., 0., ..., 0., 5., 8.],
       ...,
       [0., 1., 0., ..., 0., 2., 0.],
       [0., 1., 0., ..., 0., 2., 0.],
       [0., 1., 0., ..., 0., 2., 0.]])

In [9]:
x = np.array(df)
x = sk.preprocessing.normalize(x, axis=1)
print(x)

[[0.00995382 0.         0.         ... 0.         0.04976909 0.07963055]
 [0.00995382 0.         0.         ... 0.         0.04976909 0.07963055]
 [0.00995382 0.         0.         ... 0.         0.04976909 0.07963055]
 ...
 [0.         0.35355339 0.         ... 0.         0.70710678 0.        ]
 [0.         0.35355339 0.         ... 0.         0.70710678 0.        ]
 [0.         0.35355339 0.         ... 0.         0.70710678 0.        ]]


In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.7, random_state=117)
X_train.shape

(10560, 19)

In [11]:
X_train = X_train.reshape(X_train.shape[0], 1, 19)
X_train

array([[[0.33333333, 0.        , 0.33333333, ..., 0.        ,
         0.66666667, 0.33333333]],

       [[0.00790609, 0.        , 0.        , ..., 0.60876878,
         0.03162435, 0.05534262]],

       [[0.5       , 0.        , 0.5       , ..., 0.        ,
         0.        , 0.        ]],

       ...,

       [[0.00957032, 0.        , 0.00957032, ..., 0.        ,
         0.16269547, 0.23925804]],

       [[0.00211204, 0.        , 0.00211204, ..., 0.97787529,
         0.00422408, 0.00211204]],

       [[0.        , 0.00472767, 0.        , ..., 0.73751652,
         0.00472767, 0.0945534 ]]])

In [12]:
X_test = X_test.reshape(X_test.shape[0], 1, 19)
X_test

array([[[0.15811388, 0.        , 0.15811388, ..., 0.        ,
         0.        , 0.9486833 ]],

       [[0.03863337, 0.        , 0.        , ..., 0.        ,
         0.57950056, 0.81130078]],

       [[0.5       , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       ...,

       [[0.        , 0.00980908, 0.        , ..., 0.14713621,
         0.07847265, 0.09809081]],

       [[0.49999968, 0.        , 0.49999968, ..., 0.        ,
         0.        , 0.        ]],

       [[0.03118914, 0.        , 0.        , ..., 0.        ,
         0.        , 0.99805258]]])

In [13]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape=(1, 19)))
model.add(tf.keras.layers.LSTM(16, activation="relu"))
model.add(tf.keras.layers.Reshape((-1, 16)))
model.add(tf.keras.layers.LSTM(32, activation="relu"))
model.add(tf.keras.layers.Reshape((-1, 32)))
model.add(tf.keras.layers.Dense(32, activation="relu"))
model.add(tf.keras.layers.LSTM(16, activation="linear"))
model.add(tf.keras.layers.Dense(1, activation="linear"))
model.compile(optimizer="adamax", loss="mse", metrics=["mae"])
model.summary()
model.fit(X_train, y_train, epochs=500, batch_size=32)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 16)                2304      
                                                                 
 reshape (Reshape)           (None, 1, 16)             0         
                                                                 
 lstm_1 (LSTM)               (None, 32)                6272      
                                                                 
 reshape_1 (Reshape)         (None, 1, 32)             0         
                                                                 
 dense (Dense)               (None, 1, 32)             1056      
                                                                 
 lstm_2 (LSTM)               (None, 16)                3136      
                                                                 
 dense_1 (Dense)             (None, 1)                 1

In [22]:
model.evaluate(X_test, y_test)

771/771 [==============================] - 1s 1ms/step - loss: 12955.9551 - mae: 67.5077


[12955.955078125, 67.50769805908203]

In [15]:
model.predict(X_test)

771/771 [==============================] - 2s 2ms/step


array([[ 89.89459],
       [162.29364],
       [ 92.90207],
       ...,
       [305.13657],
       [120.84473],
       [140.10153]], dtype=float32)

In [16]:
y_test

array([273, 321,  77, ..., 413, 314,   6], dtype=int64)

In [17]:
importance = X_train[0]
importance.shape

(1, 19)

In [18]:
model.predict(np.array([X_train[0]]))

1/1 [==============================] - 0s 20ms/step


array([[131.13371]], dtype=float32)

In [19]:
for i in range(19):
    importance[0][i] = 0.0

In [20]:
cl = df.columns
cl

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       'ПроцентЗавершенияЗадачи', 'Экспертиза', 'Скорость', 'Кол-во рабочих',
       'Генподрядчик', 'Генпроектировщик'],
      dtype='object')

In [21]:
for i in range(19):
    importance[0][i] = 1.0
    print(cl[i])
    print(54.6 - model.predict(np.array([importance]))[0])
    importance[0][i] = 0.0

0
1/1 [==============================] - 0s 20ms/step
[-134.66776]
1
1/1 [==============================] - 0s 20ms/step
[-17.38057]
2
1/1 [==============================] - 0s 20ms/step
[-112.799416]
3
1/1 [==============================] - 0s 19ms/step
[-123.63941]
4
1/1 [==============================] - 0s 21ms/step
[-11999.143]
5
1/1 [==============================] - 0s 20ms/step
[-2046.5804]
6
1/1 [==============================] - 0s 25ms/step
[-1455.9133]
7
1/1 [==============================] - 0s 20ms/step
[29.92982]
8
1/1 [==============================] - 0s 19ms/step
[-6.919075]
9
1/1 [==============================] - 0s 19ms/step
[-1188.3247]
10
1/1 [==============================] - 0s 20ms/step
[-686.7194]
11
1/1 [==============================] - 0s 19ms/step
[-2876.2517]
12
1/1 [==============================] - 0s 20ms/step
[-8343.258]
ПроцентЗавершенияЗадачи
1/1 [==============================] - 0s 19ms/step
[-2483.4358]
Экспертиза
1/1 [==========================